- name: create db server 
  hosts: db
  become: yes 
  tasks:
  - name: Install MySQL
    ansible.builtin.dnf:
       name: mysql-server
       state: latest
  
  - name: Start MySQL Service
    ansible.builtin.service:
       name: mysqld
       enabled: yes 

  - name: check DB connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1 
      login_host: db 
    ignore_errors: yes 
    register: mysql_connection_output

  - name: output of root password 
    ansible.builtin.debug:
      msg: "output: {{ mysql_connection_output }}"

  #- name: set the root password 
    
  

      