- name: frontend server creation
  hosts: frontend 
  become: yes 
  tasks: 
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx 
      state: latest

  - name: start the nginx 
    ansible.builtin.service:
      name: nginx 
      state: started
      enabled: yes

  - name: remove directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: remove directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory

  - name: download the code 
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unarchive the code
    ansible.builtin.unarchive:
       src: /tmp/frontend.zip
       dest: /usr/share/nginx/html/
       remote_src: yes 

  - name: copy the file 
    ansible.builtin.copy:
       src: expense.conf
       dest: /etc/nginx/default.d

  - name: Restart Nginx Service
    ansible.builtin.service:
       name: nginx 
       state: restarted

  
    
