- name: install frontend 
  hosts: db.daws78s.cloud
  become: yes
  tasks: 
  - name: install nginx 
    ansible.builtin.dnf:
      name: nginx
  
  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove the directory 
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create the directory  
    ansible.builtin.file:   
      path: /usr/share/nginx/html
      state: directory

  - name: Download the frontend content
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: Extract the frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy the expense.conf file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d

  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: restarted
